#!/bin/sh

usage() {
	cat >&2 <<-__EOF__
		mkdisk 0.1.0 - generate alpine ext4 images
		Usage: mkdisk DISKFILE OUTPUT
	__EOF__
}

if [ -z "$2" ]; then
	usage
	exit 1
fi

if ! [ -f "$1" ]; then
	echo "diskfile $1 does not exist"
	exit 1
fi

if [ -f "$2" ]; then
	echo "output file $2 already exists"
	exit 1
fi

# set sane defaults
mirror=https://dl-cdn.alpinelinux.org/alpine
version=3.15.1
arch=x86_64

. "$1"

if [ $(id -u) != 0 ]; then
	ROOT="unshare -r"
fi

tempdir="$(mktemp -d)"
(
	branch="${version%.[0-9]}"
	filename="alpine-minirootfs-$version-$arch.tar.gz"

	wget $mirror/v$branch/releases/$arch/$filename -O "$tempdir/rootfs.tar.gz" || exit 1

	root="$tempdir"/tmp
	mkdir "$root"
	tar xf "$tempdir/rootfs.tar.gz" -C "$root"

	$ROOT apk --root "$root" upgrade -Ua
	$ROOT apk --root "$root" add $pkgs

	for file in $files; do
		IFS=: read source target < <(echo "$file")

		if [ "$target" = "" ]; then
			target="$source"
		fi

		mkdir -p "$root/$(dirname "$target")"
		cp -r "$source" "$root/$target"
	done

	cat "$1" <(echo setup) | $ROOT chroot "$root" sh

	size=$(du -sm "$root" | cut -f1)
	disk_size=$(( size + 5 ))

	truncate -s ${disk_size}M "$2"

	$ROOT mke2fs -t ext4 -d "$root" "$2"
)
rm -rf "$tempdir"
